server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/auth/**
        - id: auth-docs
          uri: ${AUTH_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/v3/api-docs/auth/**
          filters:
            - RewritePath=/v3/api-docs/auth(?<segment>/?.*), /v3/api-docs$\{segment}
        - id: trend-service
          uri: ${TREND_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/trends/**
        - id: trend-docs
          uri: ${TREND_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/v3/api-docs/trends/**
          filters:
            - RewritePath=/v3/api-docs/trends(?<segment>/?.*), /v3/api-docs$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
